# Generated by Django 4.1.1 on 2022-09-15 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="jugadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=250, null=True)),
                ("apellido", models.CharField(max_length=250, null=True)),
                ("nickname", models.CharField(max_length=250, null=True)),
                ("nacimiento", models.CharField(max_length=250, null=True)),
                ("correo", models.CharField(max_length=250, null=True)),
                ("redsocial", models.CharField(max_length=250, null=True)),
                ("videojuegofav", models.CharField(max_length=250, null=True)),
                ("plataforma_xbox", models.BooleanField(default=False, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
