# Generated by Django 3.2 on 2022-11-08 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250, null=True)),
                ('nickname', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('asunto', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=90)),
                ('contenido', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250, null=True)),
                ('correo', models.CharField(max_length=250, null=True)),
                ('numero', models.CharField(max_length=250, null=True)),
                ('pago', models.BooleanField(default=False, null=True)),
                ('total', models.CharField(max_length=250, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tienda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250, null=True)),
                ('nickname', models.CharField(max_length=250, null=True)),
                ('nacimiento', models.CharField(max_length=250, null=True)),
                ('correo', models.CharField(max_length=250, null=True)),
                ('redsocial', models.CharField(max_length=250, null=True)),
                ('videojuegofav', models.CharField(max_length=250, null=True)),
                ('plataforma_xbox', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
