# Generated by Django 3.2 on 2022-11-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'imagen', 'verbose_name_plural': 'imagenes'},
        ),
    ]
