# Generated by Django 3.2 on 2022-10-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0001_torneo'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250, null=True)),
                ('nickname', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=250, null=True)),
                ('asunto', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
