# Generated by Django 3.2 on 2022-10-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0002_alter_tienda_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='total',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
