# Generated by Django 3.2 on 2022-11-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0002_alter_imagenes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name': 'noticia', 'verbose_name_plural': 'noticias'},
        ),
    ]
