# Generated by Django 3.2 on 2022-10-13 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptesca', '0002_contactanos'),
    ]

    operations = [
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250, null=True)),
                ('correo', models.CharField(max_length=250, null=True)),
                ('numero', models.CharField(max_length=250, null=True)),
                ('producto', models.CharField(max_length=250, null=True)),
                ('pago', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
