# Generated by Django 3.2.16 on 2023-09-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0003_marca_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
