# Generated by Django 3.2 on 2022-10-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0003_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='total',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
