# Generated by Django 3.2.16 on 2023-09-14 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptesca', '0004_auto_20230912_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datosuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, null=True)),
                ('apellido', models.CharField(max_length=250, null=True)),
                ('correo', models.EmailField(max_length=250, null=True)),
                ('numero', models.CharField(max_length=250, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
