# Generated by Django 3.2 on 2022-10-14 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0004_carro_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='total',
        ),
    ]
