# Generated by Django 3.2 on 2022-10-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0005_remove_carro_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carro',
            old_name='producto',
            new_name='total',
        ),
    ]
