# Generated by Django 3.2.16 on 2023-09-15 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptesca', '0006_alter_datosuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosuser',
            old_name='nombre',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='datosuser',
            old_name='apellido',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='datosuser',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
