# Generated by Django 3.2.16 on 2023-09-18 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptesca', '0007_auto_20230915_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datosuser',
            new_name='Datocompra',
        ),
    ]
