# Generated by Django 3.2.16 on 2023-09-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0010_delete_datocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
