# Generated by Django 3.2.16 on 2023-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0011_jugadores_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='numero',
        ),
        migrations.AddField(
            model_name='jugadores',
            name='numero',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
