# Generated by Django 3.2.16 on 2023-09-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0012_auto_20230918_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='imagen_profile',
            field=models.ImageField(null=True, upload_to='perfil'),
        ),
    ]
