# Generated by Django 3.2.10 on 2023-09-20 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0013_jugadores_imagen_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='imagen_profile',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
