# Generated by Django 3.2.10 on 2023-09-26 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0015_auto_20230922_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tienda',
            name='numero',
        ),
    ]
