# Generated by Django 3.2.10 on 2023-09-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptesca', '0016_auto_20230926_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='apellido',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='correo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='nombre',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tienda',
            name='numero',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
