version: "3"

services:
  db_postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Servicio "db" para la base de datos PostgreSQL
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust  # Configura el método de autenticación de PostgreSQL como "trust" (puede ser inseguro en producción)
  
  django_app:
    build: .
    command: bash -c "python /code/manage.py migrate && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - static:/code/
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db_postgres
    
  nginx:
    container_name: nginx  # Nombre del contenedor
    restart: always  # Reinicia siempre el contenedor en caso de fallo
    image: nginx:latest
    ports:
      - "5085:5085"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - django_app

      

volumes:
  .:
  postgres_data:
  static: